version: '3'
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_FOLDER}:/var/lib/postgresql/data
    restart: always

  keycloak:
    container_name: keycloak
    build: ./docker/keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      # - "${KEYCLOAK_PORT}:8443"
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ${KEYCLOAK_DATA_FOLDER}:/opt/keycloak/data/
    depends_on:
      - postgres
    restart: always
    # command: start --optimized --hostname-port=${KEYCLOAK_PORT}
    command: start-dev

  # keycloak:
  #   container_name: keycloak
  #   image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
  #   environment:
  #     - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
  #     - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
  #   ports:
  #     - "${KEYCLOAK_PORT}:8080"
  #   volumes:
  #     - ${KEYCLOAK_DATA_FOLDER}:/opt/keycloak/data/
  #   restart: always
  #   command: start-dev

  mongodb:
    container_name: mongodb
    image: mongo:${MONGO_VERSION}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_DATA_FOLDER}:/data/db
    restart: always

  generic-api:
    container_name: generic-api
    # build: .
    build: ./docker/generic-api
    working_dir: /code
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    environment:
      DEBUG: 1
    volumes:
      - .:/code
    ports:
      - "${GENERIC_API_PORT}:8000"
    restart: always
